In [1]:
import pandas as pd
import numpy as np

In [29]:
df = pd.read_csv("data/raw_fred_data.csv")

df['date'] = pd.to_datetime(df['date'])
df = df.set_index('date')

monthly_spread = df['spread_10y3m'].resample('ME').mean()
monthly_USREC = df['recession_nber'].resample('ME').last()
target_12m = monthly_USREC.shift(-12)

df_cleaned = pd.DataFrame({
    'T10Y3M': monthly_spread,
    'USREC' : monthly_USREC,
    'target_12m' : target_12m
})

df_cleaned = df_cleaned.dropna()

In [31]:
df_cleaned.tail()

              T10Y3M  USREC  target_12m
date
2025-03-31 -0.055238    0.0         0.0
2025-04-30 -0.043333    0.0         0.0
2025-05-31  0.062381    0.0         0.0
2025-06-30 -0.037500    0.0         0.0
2025-07-31 -0.020455    0.0         0.0

required dataset: USREC,T10Y3M, 

how the prohibit model works -> create a linear fit with x = T10Y3M based on historical data. apply normal cdf to calculate the probability.

data quelity : uptill 2026-07-31

In [5]:
df = pd.read_csv("data/raw_fred_data.csv")
df['date'] = pd.to_datetime(df['date'])
df = df.set_index('date')

In [23]:
monthly_spread = df['spread_10y3m'].resample('ME').mean()
monthly_USREC = df['recession_nber'].resample('ME').last()
target_12m = df['recession_nber'].resample('ME').last().shift(-12)

In [25]:
df_cleaned = pd.DataFrame({
    'T10Y3M': monthly_spread,
    'USREC' : monthly_USREC,
    'target_12m' : target_12m
})

df_cleaned = df_cleaned.dropna()

In [28]:
df_cleaned.tail(15)

              T10Y3M  USREC  target_12m
date
2024-05-31 -0.972727    0.0         0.0
2024-06-30 -1.201053    0.0         0.0
2024-07-31 -1.183182    0.0         0.0
2024-08-31 -1.424545    0.0         0.0
2024-09-30 -1.198500    0.0         0.0
2024-10-31 -0.622727    0.0         0.0
2024-11-30 -0.264211    0.0         0.0
2024-12-31  0.000476    0.0         0.0
2025-01-31  0.286190    0.0         0.0
2025-02-28  0.118947    0.0         0.0
2025-03-31 -0.055238    0.0         0.0
2025-04-30 -0.043333    0.0         0.0
2025-05-31  0.062381    0.0         0.0
2025-06-30 -0.037500    0.0         0.0
2025-07-31 -0.020455    0.0         0.0